---
name: lint

on:
  workflow_call:

jobs:
  lint-files:
    name: lint and style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint markdown
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: '**/*.md'
